### ISSUE TITLE
Command Parser

### ISSUE THREAD

**Issue by Ktar5** [VevoxDigital/VevoxelAPI-Bukkit#8]
Usable for things such as formatting what a command should be, quickly, for example:
Command command = new Command("TOKENS SEND <INTEGER> <OFFLINE PLAYER NAME> <SPACED STRING>");

which the onCommand will process and be like "ok.. send the method tokens send, ok this is an integer, send it, ok lets get the Offline Player of this string if it exists, else throw an error, and ok there's a message at the end that can contain any amount of spaces, convert to string and send it"

**Comment by Wehttam664** [comment]
...and done.
